name: Build and Test

on:
  push:

env:
  IMAGE_NAME: garage
  RUST_VERSION: latest
  GARAGE_VERSION: v2

jobs:
  build-and-test:
    strategy:
      fail-fast: false
      matrix:
        include:
          - runner: ubuntu-latest
          - runner: ubuntu-24.04-arm

    runs-on: ${{ matrix.runner }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image (local arch)
        run: make build-local

      - name: Test Docker image
        run: make test
